version: "3"
services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    container_name: sz-front-container
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "3333:3333"
    container_name: sz-back-container
